/*4.2*/
proc import datafile='E:\Applied Regression Analysis\SAS\data-table-B1.csv' out = file_data;
	getnames=yes;
run;
proc reg data=file_data;
	model y=x2 x7 x8/r;
	output out=residual_data residual=res student=stu_res press=press_res rstudent=rstu_res h=h;
run;
proc univariate data=residual_data normal plot;
	var res;
run;
proc reg data=file_data;
	model y=x2 x7 x8/r;
	plot r.*p.;
run;
proc reg data=residual_data;
	model y=x2 x7 x8;
run;
proc reg data=residual_data;
	model y=x2 x7 x8/partial;
run;
proc print data=residual_data;
run;
/*4.20*/
proc import datafile='E:\Applied Regression Analysis\Data Sets\data-prob-4-20.xls' out = file_data dbms=XLS replace;
	getnames=yes;
run;
data file_data;
	set file_data;
	rename acid_temp=x1 acid_conc=x2 water_temp=x3 sulf_conc=x4 amt_bl_=x5;
run;
proc print data=file_data;
run;
proc reg data=file_data;
	model y=x1 x2 x3 x4 x5/r;
	output out=residual_data residual=res student=stu_res press=press_res rstudent=rstu_res h=h;
	plot r.*p.;
run;
proc univariate data=residual_data normal plot;
	var res;
run;
/*5.3*/
proc import datafile='E:\Applied Regression Analysis\Data Sets\data-prob-5-3.xls' out = file_data dbms=XLS replace;
	getnames=yes;
run;
proc gplot data=file_data;
	plot bact*min;
run;
proc reg data=file_data;
	model bact=min/r;
	output out=residual_data residual=res student=stu_res press=press_res rstudent=rstu_res h=h;
	plot r.*p.;
run;
proc univariate data=residual_data normal plot;
	var res;
run;
data file_data;
	set file_data;
	bact_ln = log(bact);
run;
proc print data=file_data;
run;
proc gplot data=file_data;
	plot bact_ln*min;
run;
proc reg data=file_data;
	model bact_ln=min/r;
	output out=residual_data residual=res student=stu_res press=press_res rstudent=rstu_res h=h;
	plot r.*p.;
run;
proc univariate data=residual_data normal plot;
	var res;
run;
